//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by bwchart.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_BWCHART_DIALOG              102
#define IDD_DLGHELP_DIALOG              103
#define IDD_DLGBWCHART_DIALOG           104
#define IDD_DLGBROWSER_DIALOG           105
#define IDD_DLGFAVORITES                106
#define IDD_DLGEDITCOMMENT_DIALOG       107
#define IDD_DLGAKAS                     108
#define IDD_DLGEDITAKAS_DIALOG          109
#define IDD_DLGMAP_DIALOG               110
#define IDD_DLGFASTAKA_DIALOG           111
#define IDD_DLGRENAME_DIALOG            112
#define IDD_EXPORTCOACHDLG_DIALOG       113
#define IDR_MAINFRAME                   128
#define IDR_POPUPREPLAY                 132
#define IDI_ICON_OK                     133
#define IDR_POPUPPLAYER                 133
#define IDR_TEXTAKAS                    133
#define IDI_ICON_DISABLE                134
#define IDR_POPUPFAV                    134
#define IDR_TEXTMAPAKAS                 134
#define IDR_POPPLAYERS                  135
#define IDR_POPUPREPLAYMULT             136
#define IDR_WATCHREP                    137
#define IDR_MENU_EVENTS                 138
#define IDD_PROGRESSBAR                 139
#define IDD_DLGOPTIONS                  140
#define IDD_DLGOPTIONS1                 141
#define IDD_MAIN_OPTIONS                142
#define IDD_DLGOPTIONS_CHART            143
#define IDC_GETEVENTS                   1001
#define IDC_LISTEVENTS                  1002
#define IDC_PLSTATS                     1003
#define IDC_SCROLLBAR1                  1004
#define IDC_SCROLLBAR2                  1005
#define IDC_ZOOM                        1006
#define IDC_MINERALS                    1007
#define IDC_GAZ                         1008
#define IDC_VERSION                     1008
#define IDC_SUPPLY                      1009
#define IDC_ACTIONS                     1010
#define IDC_SINGLECHART                 1011
#define IDC_DBLCLICK                    1012
#define IDC_UNITS                       1013
#define IDC_USESECONDS                  1014
#define IDC_SPEED                       1015
#define IDC_ADDEVENT                    1016
#define IDC_GAMEDURATION                1017
#define IDC_CHARTTYPE                   1018
#define IDC_DHELP                       1019
#define IDC_TESTREPLAYS                 1020
#define IDC_PROGRESS1                   1021
#define IDC_URL                         1022
#define IDC_BPM                         1022
#define IDC_TAB1                        1023
#define IDC_UPM                         1023
#define IDC_VTAB                        1023
#define IDC_REPS                        1024
#define IDC_HKSELECT                    1024
#define IDC_DIR                         1025
#define IDC_SORTDIST                    1025
#define IDC_BROWSE                      1026
#define IDC_RADIO1                      1027
#define IDC_BROWSEDIR                   1027
#define IDC_RADIO2                      1028
#define IDC_BROWSEPLAYER                1028
#define IDC_RADIO3                      1029
#define IDC_BROWSEDIRV11                1029
#define IDC_REFRESH                     1030
#define IDC_BROWSEDIRV12                1030
#define IDC_REPLAYCOUNT                 1031
#define IDC_BROWSEDIRV13                1031
#define IDC_PLAYERCOUNT                 1032
#define IDC_BROWSEDIRV14                1032
#define IDC_MAPCOUNT                    1033
#define IDC_PROGRESS                    1033
#define IDC_BROWSEDIRV15                1033
#define IDC_LISTPLAYERS                 1034
#define IDC_BROWSEDIRV16                1034
#define IDC_LISTMAPS                    1035
#define IDC_COMMENT1                    1036
#define IDC_COMMENT                     1037
#define IDC_EDITCOMMENT                 1038
#define IDC_EDIT1                       1039
#define IDC_ADDREPLAY                   1039
#define IDC_ADDAKAPLAYER                1040
#define IDC_LISTBOS                     1040
#define IDC_RADIO5                      1041
#define IDC_AKAPLAYERS                  1043
#define IDC_PLAYERS                     1044
#define IDC_ADDPLAYER                   1045
#define IDC_DELPLAYER                   1046
#define IDC_MAINNAME                    1046
#define IDC_ADDAKAMAP                   1047
#define IDC_AKAS                        1047
#define IDC_SUGGESTIONS                 1048
#define IDC_ADDAKA                      1049
#define IDC_AKAMAPS                     1050
#define IDC_SEARCHFOR                   1050
#define IDC_AUTOREFRESH                 1050
#define IDC_MAPS                        1051
#define IDC_UNITSONBO                   1051
#define IDC_ADDMAP                      1052
#define IDC_EXACTTIME                   1052
#define IDC_DELMAP                      1053
#define IDC_ANIMSPEED                   1053
#define IDC_TIMEWAIT                    1054
#define IDC_HOTPOINTS                   1054
#define IDC_KEYSEQ                      1055
#define IDC_PERCENTAGE                  1055
#define IDC_TIMEWAIT2                   1056
#define IDC_INSTALLPATH                 1057
#define IDC_KEYSEQ2                     1058
#define IDC_BWEXE109                    1059
#define IDC_BWPLAYER                    1060
#define IDC_SEEMAP                      1061
#define IDC_BWEXE111                    1061
#define IDC_BWEXE112                    1062
#define IDC_ANIMATE                     1063
#define IDC_BWEXE113                    1063
#define IDC_BWEXE114                    1064
#define IDC_BWEXE115                    1065
#define IDC_BWEXE116                    1066
#define IDC_SPEEDPLUS                   1068
#define IDC_SPEEDMINUS                  1069
#define IDC_AUTOKEYS                    1069
#define IDC_PAUSE                       1070
#define IDC_PLAYER1                     1070
#define IDC_AUTOCHECK                   1070
#define IDC_ASSO1                       1071
#define IDC_AUTOSTARTRWA                1071
#define IDC_LISTPLAYERS1                1072
#define IDC_PLAYER2                     1073
#define IDC_ASSO2                       1074
#define IDC_LISTPLAYERS2                1075
#define IDC_MAP                         1076
#define IDC_ASSO3                       1077
#define IDC_TEXT1                       1078
#define IDC_TEXT2                       1079
#define IDC_TEXT3                       1080
#define IDC_BUILDON                     1080
#define IDC_FPLAYER                     1081
#define IDC_MINERALON                   1081
#define IDC_PFILTERON                   1082
#define IDC_CLEAR                       1083
#define IDC_FPOSITIONS                  1083
#define IDC_POSFILTERON                 1084
#define IDC_RECURSIVE                   1085
#define IDC_MUTERRAN                    1086
#define IDC_MUZERG                      1087
#define IDC_CHECKUPDATE                 1087
#define IDC_MUTOSS                      1088
#define IDC_BGGRID                      1088
#define IDC_MAXAPMMARKER                1089
#define IDC_FORMAT                      1089
#define IDC_MUXVX                       1089
#define IDC_REPLAYS                     1090
#define IDC_BGGRADIENT                  1090
#define IDC_RWAONLY                     1090
#define IDC_RENAME                      1091
#define IDC_COLOREDEVENTLIST            1091
#define IDC_FMAP                        1091
#define IDC_DEFAULT                     1092
#define IDC_MAPFILTERON                 1092
#define IDC_USERDEF1                    1093
#define IDC_RADIOSAVE                   1093
#define IDC_MUTERRAN2                   1093
#define IDC_REPLACEMENT1                1094
#define IDC_RADIOSAVE2                  1094
#define IDC_MUZERG2                     1094
#define IDC_FILEASSO                    1095
#define IDC_MUTOSS2                     1095
#define IDC_MENU_BROWSER                1096
#define IDC_AUTOADD                     1096
#define IDC_MENU_CHARTS                 1097
#define IDC_FLT_SELECT                  1097
#define IDC_AUTOLOAD                    1097
#define IDC_MENU_FAVORITES              1098
#define IDC_FLT_BUILD                   1098
#define IDC_MENU_AKAS                   1099
#define IDC_FLT_TRAIN                   1099
#define IDC_MENU_OPTIONS                1100
#define IDC_FLT_SUSPECT                 1100
#define IDC_FLT_OTHERS                  1101
#define IDC_NEXT_SUSPECT                1102
#define IDC_SUSPECT_INFO                1103
#define IDC_SUSPECT_LIMIT               1104
#define IDC_FLT_HACK                    1104
#define IDC_REPLAYFILE                  1105
#define IDC_AUTHOR                      1106
#define IDC_FLT_CHAT                    1106
#define IDC_TITLE                       1107
#define IDC_DESC                        1108
#define IDC_DURATION                    1109
#define IDC_LIST1                       1110
#define IDC_EXPORTUNITS                 1111
#define IDC_EXPORTWORKERS               1112
#define IDC_AUTOLOADDB                  1112
#define IDC_CLEANMISSING                1113
#define IDC_BROWSEBMP                   1115
#define IDC_USEBMP                      1116
#define IDC_BMPPATH                     1117
#define IDC_PLAYERNAME                  1118
#define IDC_PREVIEW                     1119
#define IDC_COLOR_MAPNAME               1120
#define IDC_COLOR_PLAYERNAME            1121
#define IDC_COLOR_OTHER                 1122
#define IDC_DEFAULTS                    1123
#define IDC_COMBOTYPE                   1124
#define IDC_COLOR_CHART                 1125
#define IDC_DEFAULTS2                   1126
#define IDC_COMBOLSIZE                  1127
#define IDC_APMSTYLE                    1128
#define IDC_COMBO1                      1129
#define IDC_COMBOMU                     1129
#define IDC_RADIO4                      1133
#define IDC_BUTTON1                     1134
#define IDC_BO_BUILDING                 1135
#define IDC_BO_UNIT                     1136
#define IDC_BO_RESEARCH                 1137
#define IDC_BO_UPGRADE                  1138
#define IDC_BOMAXOBJ                    1139
#define IDC_SPIN1                       1140
#define IDC_BO_SUPPLY                   1141
#define IDC_FILTERONBO                  1142
#define IDC_BOREPLAYS                   1152
#define IDC_STATICBO                    1153
#define IDC_STATICVS                    1154
#define ID_F_LOADREPLAY                 32771
#define ID__ADDREPLAYEVENTS             32772
#define ID__REMOVEPLAYER                32773
#define ID__ENABLEDISABLE               32774
#define ID__ADDTOFAVORITES              32775
#define ID__REMOVEFAVORITES             32776
#define ID__EDITCOMMENTS                32777
#define ID__WATCHREPLAYINBW             32778
#define ID__UPDATEAKAS                  32779
#define ID__WATCHREPLAYINBW_AUTO        32783
#define ID__WATCHREPLAYINBW_SC          32784
#define ID__OPENDIRECTORY               32785
#define ID_G_LISTREPLAYS                32786
#define ID__FILE_MOVETORECYCLEBIN       32787
#define ID__MOVETOFOLDER                32788
#define ID__FILE_RENAME                 32789
#define ID_FF_EXPORT_TOTEXTFILE         32790
#define ID__EXPORTTO_BWCOACH            32792
#define ID__WATCHREP                    32793
#define IDS_ABOUTBOXMENU                32794
#define IDS_DELETEAKAS                  32795
#define IDS_EMPTYDB                     32796
#define IDS_ONEREPLAYADDED              32797
#define IDS_MULREPLAYADDED              32798
#define IDS_CORRUPTED                   32799
#define IDS_MOREREPLAYS                 32800
#define IDS_REMOVEREP                   32801
#define IDS_EMPTYBWPATH                 32802
#define IDS_CANTSTARTBW                 32803
#define IDS_NOBWWINDOW                  32804
#define IDS_CANTCOPY                    32805
#define IDS_REMOVEDMISSING              32806
#define IDS_AKAEXIST                    32807
#define IDS_REFRESHBROWSER              32808
#define IDS_PLAYERS                     32809
#define IDS_MAPS                        32810
#define IDS_MOVEREP                     32811
#define IDS_CORRUPTEDBIS                32812
#define IDS_CANTLOAD                    32813
#define IDS_CANTCREATFILE               32814
#define IDS_CORRUPTED3                  32815
#define IDS_DELETEALL                   32816
#define IDS_FORMATCHG                   32817
#define ID__WATCHREPLAY_BW110           32818
#define IDS_SUSPICIOUS                  32818
#define ID__WATCHREPLAY_BW109           32819
#define ID__WATCHREPLAY_BW111           32820
#define IDS_COL_TIME                    32821
#define IDS_COL_PLAYER                  32822
#define IDS_COL_ACTION                  32823
#define IDS_COL_PARAMETERS              32824
#define IDS_COL_UNITSID                 32825
#define IDS_COL_ACTIONS                 32827
#define IDS_COL_APM                     32828
#define IDS_COL_NULL                    32829
#define IDS_COL_VAPM                    32830
#define IDS_COL_MINERAL                 32831
#define IDS_COL_GAS                     32832
#define IDS_COL_SUPPLY                  32833
#define IDS_COL_UNITS                   32834
#define IDS_COL_APMPM                   32835
#define IDS_COL_APMMAX                  32836
#define IDS_COL_APMMIN                  32837
#define IDS_COL_BASE                    32838
#define IDS_COL_REPLAYNAME              32839
#define IDS_COL_PLAYER1                 32840
#define IDS_COL_APM1                    32841
#define IDS_COL_PLAYER2                 32842
#define IDS_COL_APM2                    32843
#define IDS_COL_MAP                     32844
#define IDS_COL_DURATION                32845
#define IDS_COL_TYPE                    32846
#define IDS_COL_RWAAUTHOR               32847
#define IDS_COL_GAMEDATE                32848
#define IDS_COL_ENGINE                  32849
#define IDS_COL_COMMENT                 32850
#define IDS_COL_DIRECTORY               32851
#define IDS_COL_FILEDATE                32852
#define IDS_COL_POS1                    32853
#define IDS_COL_POS2                    32854
#define IDS_COL_PLAYERNAME              32855
#define IDS_COL_AVGAPM                  32856
#define IDS_COL_PERCDEV                 32857
#define IDS_COL_GAMESPLAYED             32858
#define IDS_COL_ZERGPERC                32859
#define IDS_COL_RANPERC                 32860
#define IDS_COL_TOSSPERC                32861
#define IDS_COL_MAPNAME                 32862
#define IDS_COL_AVGGAMEDURATION         32864
#define IDS_WATCHREPLAY                 32865
#define IDS_CHARTS                      32866
#define IDS_OTHEROPTIONS                32867
#define IDS_MKDURATION                  32868
#define IDS_DROP                        32869
#define IDS_EXPAND                      32870
#define IDS_LEAVE                       32871
#define IDS_MINGAS                      32872
#define IDS_SUPPLYUNIT                  32873
#define IDS_AUDIOCOMMENT                32874
#define IDS_TOTAL                       32875
#define IDS_ANIMATE                     32876
#define IDS_STOP                        32877
#define IDS_BUILDS                      32878
#define IDS_MOVES                       32879
#define IDS_UNITS                       32880
#define IDS_CT_RESOURCES                32881
#define IDS_CT_UNITDIST                 32882
#define IDS_CT_ACTIONDIST               32883
#define IDS_CT_BUILDDIST                32884
#define IDS_CT_UPGRADES                 32885
#define IDS_CT_APMDIST                  32886
#define IDS_CT_BO                       32887
#define IDS_CT_HOTKEYS                  32888
#define IDS_CT_APM                      32889
#define IDS_COL_MICRO                   32890
#define IDS_COL_MACRO                   32891
#define ID__WATCHREPLAY_BW112           32892
#define IDS_COL_AVGAPMAST               32892
#define IDS_COL_AVGAPMASZ               32893
#define IDS_COL_AVGAPMASP               32894
#define IDS_MINIMAPPING                 32895
#define IDS_COL_BOCOUNT                 32896
#define ID__WATCHREPLAY_BW113           32896
#define IDS_COL_BOCONTENT               32897
#define IDS_COL_BOPERCENT               32898
#define IDS_BUILDBOFILE                 32899
#define IDS_HACK                        32900
#define IDS_HACKCOUNT                   32901
#define ID__WATCHREPLAY_BW114           32902
#define IDS_CT_MIX_APMHOTKEYS           32902
#define ID__WATCHREPLAY_BW115           32903
#define IDS_CT_MAPCOVERGAGE             32903
#define ID__WATCHREPLAY_BW116           32904

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         32897
#define _APS_NEXT_CONTROL_VALUE         1155
#define _APS_NEXT_SYMED_VALUE           114
#endif
#endif
